### ISSUE TITLE
Feasibility of modeling Anisotropy

### ISSUE THREAD

**Issue by LeeRuns** [CHC-CSU/Team-CHC-CSU#23]
##1. _is there consensus?_

 if yes then how do they do it?

##2._What Software were they running?
**Could we do it in OpenFoam?

**Comment by LeeRuns** [comment]
you should know that figuring this out is a really big deal.  If we could get a good simulation going that could do this:
input [non-newtonian fluids parameters, basic coating geometry range]= output[] 

it is possible that no one has done this yet.  If that is the case then i am hoping that you can find the govorning equations that are used to model the multiphysics (fluids/solids interaction).  At that point it would be a good opportunity for you and I to sit down with @mlreid358 and figure out how we can extend OpenFOAM to model multiphysics.

**Comment by zpeek** [comment]
I couldn't find any specifically relevant articles discussing the anisotropic properties of  coating fluids, but there were articles and studies done on different sold formations and some fluids. I didn't find any repeatable source that people used but there is one article that described the general conservation laws that need to be applied to model anisotropic properties. We would have to create our own program to use since every study that i saw generated their own. I think this is going to be out of the range of things we can accomplish with the time restrictions that we have. The article with the conservation laws is attached if we need to reference it.

 
[Anisotropic Fluids.pdf](https://github.com/CHC-CSU/Team-CHC-CSU/files/122168/Anisotropic.Fluids.pdf)

**Comment by LeeRuns** [comment]
thanks zach, I think I'll have a better idea what it would take to build a solver in openfoam myself once we are done with the project.
