### ISSUE TITLE
determine fluid characteristics that are inputs 4 non-newtonian

### ISSUE THREAD

**Issue by LeeRuns** [CHC-CSU/Team-CHC-CSU#26]
look at various research papers and find out what seems to be the concsensus

**Comment by ncommarato** [comment]
I've been reading a few things online in forums about this and I think its going to depend on the type of solver we use. It's hard to decipher what everything means since I'm not familiar with openFOAM but for non-Newtonian, steady-state, I've read about two options: 1) Using simpleFOAM and changing something from turbulent to laminar and 2) this solver called "nonNewtonianicoFoam" (I'll look more into it). However, I'm not sure how the solvers work but I think the inputs are going to be dependent on what equations we choose and what assumptions we make. But now, since we are going to focus on pseudoplastics I'll try to find the consensus on whats these inputs should be.

**Comment by LeeRuns** [comment]
add simplefoam fluid properties to the Wiki Page
